### ISSUE TITLE
GCode via RTDE

### ISSUE THREAD

**Issue by 22chrs** [Jacob8089/GScript#1]
Great work so far! 
May I ask a question about what you want to archive?
I am looking for a methode to send gcode to my universal robot ur3e via RTDE, so that you can interact or modify the gcode.
For example I want to send some standard 3D-printing Gcode and while printing I want to lower the z cordinates of the whole print.
Chris

**Comment by Jacob8089** [comment]
Hi Chris,

Thanks for the compliment and for reaching out. I'm also trying to achieve what you're working on. I'm following the same principle of the 3D Printer, I'll be provided with the GCodes converted to respective UR commands including the rx, ry and rz values (which I'm still working on) for the wrist-3 positions. I have UR10e as my test bench and planning to send the commands using RTDE. **I'm setting my initial coordinate system as the base of the cobot and my initial frame as my TCP values** sending over the coordinates at 500Hz as recommended In the documentation. 

So if you run the converter code in a while loop and make changes for case 3 in the switch statement(if you're referencing my code) which converts the Z values to the Z pose value for the robot I think you'll be able to achieve the what you're planning to do. I hope I have answered your query.

Please feel free to reach out back if you have any further queries.

BR | Jacob

**Comment by 22chrs** [comment]
Thanks for your answer. I think you are far more experienced in that field than me. At the moment I am using the urbasic library, which a friend used here: https://github.com/robin-gdwl/UR_Facetracking/tree/master/URBasic
The 3D printing stuff is not really important for me right know. I have other things to accomplish. But I am really curious if you get the stuff done. Maybe then I am able to give it a try by myself.

But if you are planing on printing big things with a pellet extruder and you have questions, feel free for reaching out. A while ago we build this machine:
https://chriswalter.org/projects/hugefancy/hugefancy_EN.php
